---
title: "Lab_3_Exploregapminder"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(gapminder)

library(palmerpenguins)

install.packages("gapminder")

knitr::opts_chunk$set(echo = TRUE)

```

##Exercise 1.1/1.2

gapminder |>
  filter(country %in% c("Brazil", "Austria", "China" ) & year %in% c("1970", "1979") |>
  select(country, gdpPercap)
  
#1.3

gapminder |>  
  group_by(country) |>
  mutate(lifeExp_change = lifeExp - lag(lifeExp)) |>
  filter(lifeExp_change <0)
  


#1.4
gapminder |>
  group_by(country) |>
  filter(gdpPercap==max(gdpPercap))
  




#1.5


ggplot(gapminder |>
  filter(country =="Canada")) +
  aes(x = gdpPercap, y = lifeExp) +
  geom_smooth()+
  scale_x_log10()
 
  
#2.1

summary(data)

data = palmerpenguins::penguins

data |> summarize(mean(data$flipper_length_mm, na.rm = TRUE), mean(data$body_mass_g, na.rm = TRUE), mean(data$bill_depth_mm, na.rm = TRUE))

ggplot(data) +
aes(x= flipper_length_mm, y = body_mass_g) +
geom_point()


#2.2

gapminder |>
group_by(sex) |>
summarize(sample_size = n(), sex, flipper_length_mm)

# Scatterplot with species colored to better differentiate the statistics across categories

ggplot(data) +
  aes(x = sex, y = flipper_length_mm, color = species) +
  geom_point()



# For some reason I can't knit the document when I make a raincloud! I keep trying to fix it but can't figure it out. I made a boxplot with individual points instead!

ggplot(data) +
aes(x= sex, y= flipper_length_mm, color= sex)+
geom_jitter(height = 0, width = .4) + geom_boxplot(color = "black", alpha = .5)

