---
title: "Lab4_GreenReputation"
author: Christopher O'Donnell
output: html_document
---

```{r setup, include=FALSE}
dictionary <- readr::read_csv(here::here("data", "green_dictionary.csv"))
green_data <- readr::read_csv(here::here("data", "green_data.csv"))
knitr::opts_chunk$set(echo = TRUE)
install.packages("psych)


library(psych)



```

green_data
dictionary

head(green_data)

summary(green_data)

###Number 1


#Used much assistance from 2/15 lecture, I was incredibly lost attempting this on my own!

distinct(data.frame(dictionary))

green_data %>%
pull(open10) %>%
unique()

green_data %>%
  select(-id) %>%
  unlist() %>%
  unique()
#-99 can be seen through the plot from above!
green_data = green_data %>%
mutate(
across(
-id,
\(x) na_if(x, -99) 
)
)


#\(x) is the creation of a new function


###Number 2

summary(dictionary, intel1)

reversed = dictionary %>%
filter(Keying == -1) %>%
pull(Item)

green_data = green_data %>%
mutate(
across(
all_of(reversed),
\(x) recode(x, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1)

)
)

reverse_item = \(x) {
recode(x, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1)
}

reverse_item(1:5)


green_data = green_data %>%
rowwise() %>%
mutate(
green_total = mean (c_across(green1:green5), na.rm = TRUE),
comp_total= mean (c_across(comp1:comp10), na.rm = TRUE),
intel_total= mean (c_across(intel1:intel10), na.rm = TRUE),
open_total= mean (c_across(open1:open10), na.rm = TRUE),
.after = id
)%>%
ungroup()


###Number 3

green_data = green_data %>%
mutate(
across( 
green_total:open_total,
\(x)100*(x-1) / (5-1),
.names="{.col}_pomp"
),
.after=open_total
)


green_data = green_data %>%
mutate(
across( 
green_total:open_total,
\(x)datawizard::change_scale(x, range = c(1,5), to = c(0,100))


###Number 4 

ggplot(green_data) +
aes(x = green_total_pomp) +
geom_histogram()

###Number 5
green_data %>%
drop_na(student)%>%
filter(!is.na(student)) %>%
ggplot() +
aes(x = open_total_pomp,y = green_total_pomp, color= factor(student))+
geom_point()+
geom_smooth(method = "lm")


###Number 6: Rainfall Plot

green_data %>%
na.omit(student)%>%
filter(!is.na(student)) %>%
ggplot() +
aes(x = student,y = green_total_pomp, color= factor(student))+
geom_boxplot(color= "black")+
geom_jitter(height = .15)+
ggdist::state_slab(height= .3, color= "black", size= .2, alpha= .5, position_nudge(y=.2))


###Number 7

summary(green_total_pomp)



